### ISSUE TITLE
[Question] dataset size? 

### ISSUE THREAD

**Issue by choco9966** [QwenLM/AutoIF#11] opened 2024-07-23 13:52 UTC
Could you provide the sizes of the data generated by Python codes 1 to 9 when using GPT-4 and Qwen2-72B?

The data generated from running 1_RFT.py was 10,000, but after running 3_cross_validation, it was reduced to 700. I am wondering if this is due to a code issue or if it's expected behavior. Sharing the data sizes of each process would be very helpful for my work. Thank you.

**Comment by dongguanting** [comment] 2024-07-25 05:59
Hi !
<img width="371" alt="image" src="https://github.com/user-attachments/assets/f0d83b35-e4bf-4fc9-832f-fd72107c557a">
In fact, in the main text, we have already presented the total number of augmented samples under different supervision models and the final number of quality-filtered SFT and DPO samples. We will provide a more detailed breakdown of sample numbers in the future. 

I believe that the higher number of samples filtered by the executor for quality may indicate issues with the quality of the instructions you generated. You can compare the sample quality before and after quality validation, and there should be a noticeable improvement.

**Comment by kimlee1874** [comment] 2024-08-06 06:35
> Could you provide the sizes of the data generated by Python codes 1 to 9 when using GPT-4 and Qwen2-72B?
> 
> The data generated from running 1_RFT.py was 10,000, but after running 3_cross_validation, it was reduced to 700. I am wondering if this is due to a code issue or if it's expected behavior. Sharing the data sizes of each process would be very helpful for my work. Thank you.

Hello!
Are you using GPT4 as a supervision model? In fact, when I used the Qwen2 72B as a supervision model, the pass rate was only 4.5% in the third step.

This has something to do with the prompt. By adjusting the prompt, the quality of the generated instructions can be improved.
Currently adjusting the prompt to try to reproduce the effect in the paper...

**Comment by qy1026** [comment] 2024-08-20 07:18
> In fact, in the main text, we have already presented the total number of augmented samples under different supervision models and the final number of quality-filtered SFT and DPO samples. We will provide a more detailed breakdown of sample numbers in the future.
> 
> I believe that the higher number of samples filtered by the executor for quality may indicate issues with the quality of the instructions you generated. You can compare the sample quality before and after quality validation, and there should be a noticeable improvement.

hello, is Qwen2-72B refers to Qwen2-72B-Instruct ?

**Comment by dongguanting** [comment] 2024-09-02 12:52
> > In fact, in the main text, we have already presented the total number of augmented samples under different supervision models and the final number of quality-filtered SFT and DPO samples. We will provide a more detailed breakdown of sample numbers in the future.
> > I believe that the higher number of samples filtered by the executor for quality may indicate issues with the quality of the instructions you generated. You can compare the sample quality before and after quality validation, and there should be a noticeable improvement.
> 
> hello, is Qwen2-72B refers to Qwen2-72B-Instruct ?

It is the Qwen-instruct version, but it is our internally developed in-house version since the data produced by our AutoIF has been merged into the SFT data of Qwen-instruct.

**Closed** 2024-09-27 03:41 UTC
